In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder as le

In [2]:
df = pd.read_csv('../datasets/train.csv')

In [3]:
df.head()

,ano,sequencial_candidato,nome,uf,partido,quantidade_doacoes,quantidade_doadores,total_receita,media_receita,recursos_de_outros_candidatos.comites,...,quantidade_despesas,quantidade_fornecedores,total_despesa,media_despesa,cargo,sexo,grau,estado_civil,ocupacao,votos
0,2006,10001,JOSÉ LUIZ NOGUEIRA DE SOUSA,AP,PT,6,6,16600.00,2766.67,0.0,...,14,14,16583.60,1184.54,DEPUTADO FEDERAL,MASCULINO,ENSINO MÉDIO COMPLETO,CASADO(A),VEREADOR,8579
1,2006,10002,LOIVA DE OLIVEIRA,RO,PT,13,13,22826.00,1755.85,6625.0,...,24,23,20325.99,846.92,DEPUTADO FEDERAL,FEMININO,SUPERIOR COMPLETO,SOLTEIRO(A),SERVIDOR PÚBLICO ESTADUAL,2757
2,2006,10002,MARIA DALVA DE SOUZA FIGUEIREDO,AP,PT,17,16,158120.80,9301.22,2250.0,...,123,108,146011.70,1187.09,DEPUTADO FEDERAL,FEMININO,SUPERIOR COMPLETO,VIÚVO(A),PEDAGOGO,17428
3,2006,10002,ROMALDO MILANI,MS,PRONA,6,6,3001.12,500.19,0.0,...,8,8,3001.12,375.14,DEPUTADO FEDERAL,MASCULINO,ENSINO MÉDIO INCOMPLETO,CASADO(A),MILITAR REFORMADO,1193
4,2006,10003,ANSELMO DE JESUS ABREU,RO,PT,48,48,119820.00,2496.25,0.0,...,133,120,116416.64,875.31,DEPUTADO FEDERAL,MASCULINO,ENSINO FUNDAMENTAL COMPLETO,CASADO(A),DEPUTADO,29401

In [4]:
## codifica cada nome diferente como um número
name_encoder = le()
feature = 'nome'
name_encoder.fit(df[feature])
df[feature] = name_encoder.transform(df[feature])

In [7]:
def column2dummy(dataframe, column_name):
    '''
    Função que transforma uma coluna de tipo texto ou fator em variáveis dummy
    '''
    values = le()
    values = values.fit(dataframe[column_name])
    values = values.classes_
    for i in range(len(values) - 1):
        value = values[i]
        col_str = column_name + '_' + value
        dataframe[col_str] = np.where(df[column_name].str.contains(value), 1, 0)
        
    return dataframe.drop(column_name, axis = 1)

In [8]:
to_dummy = ['uf', 'partido', 'cargo', 'grau', 'estado_civil', 'ocupacao', 'sexo']
for variable in to_dummy:
    df = column2dummy(df, variable)
df.head()

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:11: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  # This is added back by InteractiveShellApp.init_path()

,ano,sequencial_candidato,nome,quantidade_doacoes,quantidade_doadores,total_receita,media_receita,recursos_de_outros_candidatos.comites,recursos_de_pessoas_fisicas,recursos_de_pessoas_juridicas,...,"ocupacao_TÉCNICO DE OBRAS CIVIS, ESTRADAS, SANEAMENTO E ASSEMELHADOS",ocupacao_TÉCNICO EM AGRONOMIA E AGRIMENSURA,ocupacao_TÉCNICO EM EDIFICAÇÕES,ocupacao_TÉCNICO EM INFORMÁTICA,ocupacao_VENDEDOR DE COMÉRCIO VAREJISTA E ATACADISTA,"ocupacao_VENDEDOR PRACISTA, REPRESENTANTE, CAIXEIRO-VIAJANTE E ASSEMELHADOS",ocupacao_VEREADOR,ocupacao_VETERINÁRIO,ocupacao_VIGILANTE,sexo_FEMININO
0,2006,10001,3592,6,6,16600.00,2766.67,0.0,9000.0,6300.00,...,0,0,0,0,0,0,1,0,0,0
1,2006,10002,4114,13,13,22826.00,1755.85,6625.0,15000.0,1000.00,...,0,0,0,0,0,0,0,0,0,1
2,2006,10002,4732,17,16,158120.80,9301.22,2250.0,34150.0,62220.80,...,0,0,0,0,0,0,0,0,0,1
3,2006,10002,5986,6,6,3001.12,500.19,0.0,1150.0,1101.12,...,0,0,0,0,0,0,0,0,0,0
4,2006,10003,453,48,48,119820.00,2496.25,0.0,50878.0,0.00,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df.to_csv('../datasets/train_factors.csv')